version: '3'
services:
  app:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app:cached
      - ./static/:/app/static:cached
    command: python3 manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./docker/app/.env
    networks:
      - gr_network
    depends_on:
      - mysql
  jumanpp-api:
    image: gkmr/jumanpp-api
    ports:
      - 4567:4567
  mysql:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    networks:
      - gr_network
    volumes:
      - ./docker/mysql/mysql_data:/var/lib/mysql
      - ./docker/mysql/sqls/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "graduation_research"
  elasticsearch:
    image: elasticsearch:5.6.11
    networks:
      - gr_network
    ports:
      - 9200:9200
    expose:
     - 9300
    volumes:
      - ./docker/elasticsearch/es_data/:/usr/share/elasticsearch/data/
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  kibana:
    image: kibana:5.6.11
    networks:
      - gr_network
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
networks:
  gr_network:
