# Generated by Django 2.0.6 on 2018-06-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='uid',
            new_name='username',
        ),
    ]
