# Generated by Django 2.0.6 on 2018-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
