# Generated by Django 2.0.6 on 2018-06-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0002_auto_20180605_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
