# Generated by Django 2.1 on 2018-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0004_auto_20180819_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='ta_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
