# Generated by Django 2.0.6 on 2018-06-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
