# Generated by Django 2.1.1 on 2018-09-15 16:35

from django.db import migrations, models
import djongo.models.fields
import review_based_recommender.models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0005_auto_20180819_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotDocument',
            fields=[
                ('spot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('num_of_reviews', models.IntegerField()),
                ('reviews', djongo.models.fields.ArrayModelField(model_container=review_based_recommender.models.ReviewDocument)),
            ],
        ),
    ]
