# Generated by Django 2.0.6 on 2018-06-10 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0005_city_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_based_recommender.City'),
        ),
    ]
