# Generated by Django 2.0.7 on 2018-08-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0006_spot_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('license', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_based_recommender.Spot')),
            ],
            options={
                'db_table': 'spot_images',
            },
        ),
    ]
