# Generated by Django 2.0.7 on 2018-08-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0007_spotimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotimage',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
