# Generated by Django 2.0.7 on 2018-08-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0008_spotimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotimage',
            name='owner',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotimage',
            name='owner_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
