# Generated by Django 2.1 on 2018-08-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0009_auto_20180801_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='city',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
