# Generated by Django 2.1 on 2018-08-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0010_auto_20180804_1532'),
    ]

    operations = [
        migrations.RenameModel('City', 'CityTask')
    ]
