# Generated by Django 2.1 on 2018-08-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0010_auto_20180804_1532'),
        ('review_based_recommender', '0011_auto_20180804_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_based_recommender.CityTask'),
        ),
    ]
