# Generated by Django 2.1 on 2018-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0012_auto_20180804_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='city',
            new_name='city_task',
        ),
    ]
