# Generated by Django 2.1 on 2018-08-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0014_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('name_kana', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review_based_recommender.Prefecture')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
