# Generated by Django 2.1 on 2018-08-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0015_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_based_recommender.City'),
        ),
    ]
