# Generated by Django 2.1 on 2018-08-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0016_spot_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAppend',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='review_based_recommender.City')),
                ('ta_area_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finish', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'city_appends',
            },
        ),
    ]
