# Generated by Django 2.1 on 2018-08-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0017_cityappend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review_based_recommender.City')),
            ],
            options={
                'db_table': 'zip_codes',
            },
        ),
    ]
