# Generated by Django 2.1 on 2018-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0018_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='all_lang_total_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='is_updatable',
            field=models.BooleanField(default=False),
        ),
    ]
