# Generated by Django 2.1 on 2018-08-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0019_auto_20180810_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='city_task',
        ),
    ]
