# Generated by Django 2.1 on 2018-08-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0020_remove_spot_city_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityTask',
        ),
    ]
