# Generated by Django 2.1 on 2018-08-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0021_delete_citytask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='spot',
            table='spots',
        ),
    ]
