# Generated by Django 2.1 on 2018-08-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0022_auto_20180811_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefectureAppend',
            fields=[
                ('prefecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='review_based_recommender.Prefecture')),
                ('base_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'prefecture_appends',
            },
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
        migrations.AlterModelTable(
            name='spot',
            table=None,
        ),
    ]
