# Generated by Django 2.1 on 2018-08-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0023_auto_20180811_1747'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities_old',
        ),
        migrations.AlterModelTable(
            name='cityappend',
            table='city_appends_old',
        ),
        migrations.AlterModelTable(
            name='prefecture',
            table='prefectures_old',
        ),
        migrations.AlterModelTable(
            name='prefectureappend',
            table='prefecture_appends_old',
        ),
        migrations.AlterModelTable(
            name='zipcode',
            table='zip_codes_old',
        ),
    ]
