# Generated by Django 2.1 on 2018-08-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0024_auto_20180811_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.City'),
        ),
    ]
