# Generated by Django 2.1 on 2018-08-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_based_recommender', '0025_auto_20180811_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='cityappend',
            name='city',
        ),
        migrations.RemoveField(
            model_name='prefectureappend',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CityAppend',
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
        migrations.DeleteModel(
            name='PrefectureAppend',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
