# Generated by Django 2.1 on 2018-08-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='city',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
