# Generated by Django 2.1 on 2018-08-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='cityappend',
            table='city_appends',
        ),
        migrations.AlterModelTable(
            name='prefecture',
            table='prefectures',
        ),
        migrations.AlterModelTable(
            name='prefectureappend',
            table='prefecture_appends',
        ),
        migrations.AlterModelTable(
            name='zipcode',
            table='zip_codes',
        ),
    ]
